### PR TITLE
Fixed position of Close button (X) in About screen. Fixed layout of T…

### PR DESCRIPTION
**Pull request by kiancheong**
…itleValueTableViewCell with regards to Safe Area.

### CODE REVIEW

**Comment by ecnepsnai** [comment]
Hey @kiancheong, thanks for the PR! I fixed the issue with the about screen a while back, just forgot to push that change. Can you please update this PR to remove the changes to the about screen but keep the changes to the titlevaluecell ?

P.S. we're working in branch 1.8.0

Thanks!

**Comment by cheath85** [comment]
<

**Comment by cheath85** [comment]
Ok

**Comment by KaaSHH** [comment]
.github/ISSUE_TEMPLATE/bug_report.md

**Comment by ecnepsnai** [comment]
@kiancheong My apologies, I totally forgot about this PR! I'm currently working on rewriting the app's frontend in swift and have copied the changes you made to the TitleValue cell there. See commit 10f24b6.

**Pull request closed without merging**
